# KAFKA_CREATE_TOPICS: Topic 1 will have 1 partition and 3 replicas, Topic 2 will have 1 partition, 1 replica and
#  a cleanup.policy set to compact
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"
    container_name: zookeeper


  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.71.73 #  {ipconfig getifaddr en0指令的结果} 本机ip
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"  # Kafka运行后自动创建topics Topic 1 will have 1 partition and 3 replicas
    depends_on:
      - zookeeper
    container_name: kafka1


  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.71.73 #  {ipconfig  en0指令的结果} 本机ip
      KAFKA_ADVERTISED_PORT: 9093  # 宿主机端口
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
    depends_on:
      - zookeeper
    container_name: kafka2